/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.apache.aru.health_system;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author Maria Catalina
 */
public class MainGUI extends javax.swing.JFrame {

    private final SparqlQueries sparql;
    private QueryBuilder query;
    private HtmlBuilder html;
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        this.sparql = new SparqlQueries();
        this.query = new QueryBuilder();
        this.html = new HtmlBuilder();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDoctors = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonDoctors = new javax.swing.JButton();
        jButtonHospitals = new javax.swing.JButton();
        jButtonDepartments = new javax.swing.JButton();
        jButtonTreatments = new javax.swing.JButton();
        jPanelCardLayout = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelDoctors = new javax.swing.JPanel();
        jPanelSearch = new javax.swing.JPanel();
        jComboBoxDoctorsSpeciality = new javax.swing.JComboBox<>();
        jLabelSpeciality = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jComboBoxDoctorsLocation = new javax.swing.JComboBox<>();
        jLabelLanguage = new javax.swing.JLabel();
        jComboBoxDoctorsLanguage = new javax.swing.JComboBox<>();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonAll = new javax.swing.JRadioButton();
        jButtonSearchDoctors = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jScrollPaneListDoctors = new javax.swing.JScrollPane();
        jListTextDoctors = new javax.swing.JList<>();
        jPanelHospitals = new javax.swing.JPanel();
        jPanelSearchHospitals = new javax.swing.JPanel();
        jComboBoxHospitalsSpeciality = new javax.swing.JComboBox<>();
        jLabelSpeciality1 = new javax.swing.JLabel();
        jLabelLocation1 = new javax.swing.JLabel();
        jComboBoxHospitalsLocation = new javax.swing.JComboBox<>();
        jButtonSearchHospitals = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxHospitalsOpening = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxHospitalsClosing = new javax.swing.JComboBox<>();
        jButtonResetHospitals = new javax.swing.JButton();
        jScrollPaneListTextHospitals = new javax.swing.JScrollPane();
        jListTextHospitals = new javax.swing.JList<>();
        jPanelDepartments = new javax.swing.JPanel();
        jScrollPaneListTextDepartments = new javax.swing.JScrollPane();
        jListTextDepartments = new javax.swing.JList<>();
        jPanelSearchDepartments = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTreatments = new javax.swing.JPanel();
        jPanelSearchTreatments = new javax.swing.JPanel();
        jComboBoxTreatmentsSymptoms = new javax.swing.JComboBox<>();
        jLabelSymptoms = new javax.swing.JLabel();
        jButtonSearchTreatments = new javax.swing.JButton();
        jButtonResetTreatments = new javax.swing.JButton();
        jScrollPaneListTextTreatments = new javax.swing.JScrollPane();
        jListTextTreatments = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));

        jPanelMenu.setBackground(new java.awt.Color(153, 153, 255));

        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonDoctors.setText("Doctors");
        jButtonDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorsActionPerformed(evt);
            }
        });

        jButtonHospitals.setText("Hospitals");
        jButtonHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHospitalsActionPerformed(evt);
            }
        });

        jButtonDepartments.setText("Departments");
        jButtonDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartmentsActionPerformed(evt);
            }
        });

        jButtonTreatments.setText("Treatments");
        jButtonTreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreatmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDoctors)
                    .addComponent(jButtonHospitals)
                    .addComponent(jButtonDepartments)
                    .addComponent(jButtonTreatments)
                    .addComponent(jButtonHome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCardLayout.setPreferredSize(new java.awt.Dimension(700, 549));
        jPanelCardLayout.setLayout(new java.awt.CardLayout());

        jPanelHome.setPreferredSize(new java.awt.Dimension(700, 549));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/health_on_the_net.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(732, 549));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCardLayout.add(jPanelHome, "jPanelHome");

        jPanelDoctors.setPreferredSize(new java.awt.Dimension(700, 549));

        jComboBoxDoctorsSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Cardiology", "Dermatology", "Gastroenterology", "Gynecology", "Neurology", "Opthalmology", "Orthopedics", "Pediatrics", "Psychiatry", "Radiology", "Stomatology", "Urology" }));
        jComboBoxDoctorsSpeciality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDoctorsSpecialityItemStateChanged(evt);
            }
        });
        jComboBoxDoctorsSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDoctorsSpecialityActionPerformed(evt);
            }
        });

        jLabelSpeciality.setText("Search by Speciality");

        jLabelLocation.setText("Search by Location");

        jComboBoxDoctorsLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Birmingham", "Bristol", "Cambridge", "London" }));
        jComboBoxDoctorsLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDoctorsLocationItemStateChanged(evt);
            }
        });

        jLabelLanguage.setText("Language Spoken");

        jComboBoxDoctorsLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Chinese", "Dutch", "English", "French", "Italian", "Russian", "Spanish" }));
        jComboBoxDoctorsLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDoctorsLanguageItemStateChanged(evt);
            }
        });

        jLabelGender.setText("Gender");

        buttonGroupDoctors.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupDoctors.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });

        buttonGroupDoctors.add(jRadioButtonAll);
        jRadioButtonAll.setText("All");
        jRadioButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAllActionPerformed(evt);
            }
        });

        jButtonSearchDoctors.setText("Search");
        jButtonSearchDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDoctorsActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelLocation))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelSpeciality))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelLanguage))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDoctorsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDoctorsSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDoctorsLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonFemale)
                            .addComponent(jRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonAll)
                            .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addComponent(jButtonSearchDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabelGender)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelSpeciality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDoctorsSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDoctorsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDoctorsLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelGender)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchDoctors)
                    .addComponent(jButtonReset))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jListTextDoctors.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListDoctors.setViewportView(jListTextDoctors);

        javax.swing.GroupLayout jPanelDoctorsLayout = new javax.swing.GroupLayout(jPanelDoctors);
        jPanelDoctors.setLayout(jPanelDoctorsLayout);
        jPanelDoctorsLayout.setHorizontalGroup(
            jPanelDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorsLayout.createSequentialGroup()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneListDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
        );
        jPanelDoctorsLayout.setVerticalGroup(
            jPanelDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneListDoctors)
        );

        jPanelCardLayout.add(jPanelDoctors, "jPanelDoctors");

        jPanelHospitals.setPreferredSize(new java.awt.Dimension(700, 549));

        jComboBoxHospitalsSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Cardiology", "Dermatology", "Gastroenterology", "Gynecology", "Neurology", "Opthalmology", "Orthopedics", "Pediatrics", "Psychiatry", "Radiology", "Stomatology", "Urology" }));
        jComboBoxHospitalsSpeciality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHospitalsSpecialityItemStateChanged(evt);
            }
        });
        jComboBoxHospitalsSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHospitalsSpecialityActionPerformed(evt);
            }
        });

        jLabelSpeciality1.setText("Search by Speciality");

        jLabelLocation1.setText("Search by Location");

        jComboBoxHospitalsLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Birmingham", "Bristol", "Cambridge", "London" }));
        jComboBoxHospitalsLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHospitalsLocationItemStateChanged(evt);
            }
        });

        jButtonSearchHospitals.setText("Search");
        jButtonSearchHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchHospitalsActionPerformed(evt);
            }
        });

        jLabel2.setText("Opening hours");

        jComboBoxHospitalsOpening.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxHospitalsOpening.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHospitalsOpeningItemStateChanged(evt);
            }
        });

        jLabel3.setText("Closing hours");

        jComboBoxHospitalsClosing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxHospitalsClosing.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHospitalsClosingItemStateChanged(evt);
            }
        });

        jButtonResetHospitals.setText("Reset");
        jButtonResetHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetHospitalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchHospitalsLayout = new javax.swing.GroupLayout(jPanelSearchHospitals);
        jPanelSearchHospitals.setLayout(jPanelSearchHospitalsLayout);
        jPanelSearchHospitalsLayout.setHorizontalGroup(
            jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                .addGroup(jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonSearchHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelLocation1))
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelSpeciality1))
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxHospitalsLocation, 0, 153, Short.MAX_VALUE)
                            .addComponent(jComboBoxHospitalsSpeciality, 0, 153, Short.MAX_VALUE)))
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonResetHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchHospitalsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxHospitalsClosing, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxHospitalsOpening, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        jPanelSearchHospitalsLayout.setVerticalGroup(
            jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchHospitalsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelSpeciality1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHospitalsSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocation1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHospitalsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHospitalsOpening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHospitalsClosing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanelSearchHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchHospitals)
                    .addComponent(jButtonResetHospitals))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jListTextHospitals.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListTextHospitals.setViewportView(jListTextHospitals);

        javax.swing.GroupLayout jPanelHospitalsLayout = new javax.swing.GroupLayout(jPanelHospitals);
        jPanelHospitals.setLayout(jPanelHospitalsLayout);
        jPanelHospitalsLayout.setHorizontalGroup(
            jPanelHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHospitalsLayout.createSequentialGroup()
                .addComponent(jPanelSearchHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListTextHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
        jPanelHospitalsLayout.setVerticalGroup(
            jPanelHospitalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSearchHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneListTextHospitals)
        );

        jPanelCardLayout.add(jPanelHospitals, "jPanelHospitals");

        jListTextDepartments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListTextDepartments.setViewportView(jListTextDepartments);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/health_insurance.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(630, 350));

        javax.swing.GroupLayout jPanelSearchDepartmentsLayout = new javax.swing.GroupLayout(jPanelSearchDepartments);
        jPanelSearchDepartments.setLayout(jPanelSearchDepartmentsLayout);
        jPanelSearchDepartmentsLayout.setHorizontalGroup(
            jPanelSearchDepartmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanelSearchDepartmentsLayout.setVerticalGroup(
            jPanelSearchDepartmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDepartmentsLayout = new javax.swing.GroupLayout(jPanelDepartments);
        jPanelDepartments.setLayout(jPanelDepartmentsLayout);
        jPanelDepartmentsLayout.setHorizontalGroup(
            jPanelDepartmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepartmentsLayout.createSequentialGroup()
                .addComponent(jPanelSearchDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListTextDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDepartmentsLayout.setVerticalGroup(
            jPanelDepartmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSearchDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepartmentsLayout.createSequentialGroup()
                .addComponent(jScrollPaneListTextDepartments)
                .addContainerGap())
        );

        jPanelCardLayout.add(jPanelDepartments, "jPanelDepartments");

        jComboBoxTreatmentsSymptoms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Allergies", "Anxiety", "Cold", "Coughing", "Cramps", "Heartburn", "Migrane" }));
        jComboBoxTreatmentsSymptoms.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTreatmentsSymptomsItemStateChanged(evt);
            }
        });
        jComboBoxTreatmentsSymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTreatmentsSymptomsActionPerformed(evt);
            }
        });

        jLabelSymptoms.setText("Search by Symptoms");

        jButtonSearchTreatments.setText("Search");
        jButtonSearchTreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchTreatmentsActionPerformed(evt);
            }
        });

        jButtonResetTreatments.setText("Reset");
        jButtonResetTreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetTreatmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchTreatmentsLayout = new javax.swing.GroupLayout(jPanelSearchTreatments);
        jPanelSearchTreatments.setLayout(jPanelSearchTreatmentsLayout);
        jPanelSearchTreatmentsLayout.setHorizontalGroup(
            jPanelSearchTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchTreatmentsLayout.createSequentialGroup()
                .addGroup(jPanelSearchTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchTreatmentsLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelSymptoms))
                    .addGroup(jPanelSearchTreatmentsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jComboBoxTreatmentsSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchTreatmentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSearchTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonResetTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSearchTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        jPanelSearchTreatmentsLayout.setVerticalGroup(
            jPanelSearchTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchTreatmentsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelSymptoms)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxTreatmentsSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonSearchTreatments, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonResetTreatments, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jListTextTreatments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListTextTreatments.setViewportView(jListTextTreatments);

        javax.swing.GroupLayout jPanelTreatmentsLayout = new javax.swing.GroupLayout(jPanelTreatments);
        jPanelTreatments.setLayout(jPanelTreatmentsLayout);
        jPanelTreatmentsLayout.setHorizontalGroup(
            jPanelTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTreatmentsLayout.createSequentialGroup()
                .addComponent(jPanelSearchTreatments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListTextTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanelTreatmentsLayout.setVerticalGroup(
            jPanelTreatmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSearchTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneListTextTreatments)
        );

        jPanelCardLayout.add(jPanelTreatments, "jPanelTreatments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        CardLayout card = (CardLayout)jPanelCardLayout.getLayout();
        card.show(jPanelCardLayout, "jPanelHome"); 
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorsActionPerformed
        CardLayout card = (CardLayout)jPanelCardLayout.getLayout();
        card.show(jPanelCardLayout, "jPanelDoctors");
        
        // Get data from query
        String doctorQuery = query.buildDoctorsQuery();
        ArrayList data = sparql.listDoctors(doctorQuery);
        
        // Insert data in jList
        jListTextDoctors.setModel(html.createDoctorListItem(data));
    }//GEN-LAST:event_jButtonDoctorsActionPerformed

    private void jButtonHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHospitalsActionPerformed
         CardLayout card = (CardLayout)jPanelCardLayout.getLayout();
         card.show(jPanelCardLayout, "jPanelHospitals");
        
        // Get data from query
        String hospitalsQuery = query.buildHospitalsQuery();
        ArrayList data = sparql.listHospitals(hospitalsQuery);
        
        // Insert data in jList
        jListTextHospitals.setModel(html.createHospitalListItem(data));
    }//GEN-LAST:event_jButtonHospitalsActionPerformed

    private void jComboBoxDoctorsSpecialityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDoctorsSpecialityItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }
            
            query.setSpeciality(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxDoctorsSpecialityItemStateChanged

    private void jComboBoxDoctorsLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDoctorsLocationItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }
            
            query.setLocation(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxDoctorsLocationItemStateChanged

    private void jComboBoxDoctorsLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDoctorsLanguageItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }
            
            query.setLanguage(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxDoctorsLanguageItemStateChanged

    private void jButtonSearchDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDoctorsActionPerformed
        // Get data from query
        String doctorQuery = query.buildDoctorsQuery();
        ArrayList data = sparql.listDoctors(doctorQuery);
        
        // Insert data in jList
        jListTextDoctors.setModel(html.createDoctorListItem(data));
    }//GEN-LAST:event_jButtonSearchDoctorsActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        query.setGender("Male");
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        query.setGender("Female");
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jRadioButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllActionPerformed
        query.setGender("");
    }//GEN-LAST:event_jRadioButtonAllActionPerformed
                                                         
  
    private void jComboBoxDoctorsSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDoctorsSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDoctorsSpecialityActionPerformed

    private void jButtonSearchHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchHospitalsActionPerformed
        // Get data from query
        String hospitalQuery = query.buildHospitalsQuery();
        ArrayList data = sparql.listHospitals(hospitalQuery);

        // Insert data in jList
       jListTextHospitals.setModel(html.createHospitalListItem(data));
    }//GEN-LAST:event_jButtonSearchHospitalsActionPerformed

    private void jButtonDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartmentsActionPerformed
        CardLayout card = (CardLayout)jPanelCardLayout.getLayout();
        card.show(jPanelCardLayout, "jPanelDepartments");
        
        // Get data from query
        String departmentQuery = query.buildDepartmentsQuery();
        ArrayList data = sparql.listDepartments(departmentQuery);
        
        // Insert data in jList
        jListTextDepartments.setModel(html.createDepartmentListItem(data));
    }//GEN-LAST:event_jButtonDepartmentsActionPerformed

    private void jButtonSearchTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchTreatmentsActionPerformed
         // Get data from query
        String treatmentsQuery = query.buildTreatmentsQuery();
        ArrayList data = sparql.listTreatments(treatmentsQuery);
        
        boolean showDoctors = !query.getSymptoms().equals("");

        // Insert data in jList
       jListTextTreatments.setModel(html.createTreatmentListItem(data, showDoctors));
    }//GEN-LAST:event_jButtonSearchTreatmentsActionPerformed

    private void jComboBoxHospitalsSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHospitalsSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHospitalsSpecialityActionPerformed

    private void jComboBoxHospitalsSpecialityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHospitalsSpecialityItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }

            query.setSpecialityHospitals(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxHospitalsSpecialityItemStateChanged

    private void jComboBoxHospitalsLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHospitalsLocationItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }
            
            query.setAddress(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxHospitalsLocationItemStateChanged

    private void jComboBoxHospitalsOpeningItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHospitalsOpeningItemStateChanged
         if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            
            query.setOpeningHours(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxHospitalsOpeningItemStateChanged

    private void jComboBoxHospitalsClosingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHospitalsClosingItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();

            query.setClosingHours(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxHospitalsClosingItemStateChanged

    private void jButtonTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreatmentsActionPerformed
        CardLayout card = (CardLayout)jPanelCardLayout.getLayout();
        card.show(jPanelCardLayout, "jPanelTreatments");
        
        // Get data from query
        String treatmentQuery = query.buildTreatmentsQuery();
        ArrayList data = sparql.listTreatments(treatmentQuery);
        
        // Insert data in jList
        jListTextTreatments.setModel(html.createTreatmentListItem(data, false));
    }//GEN-LAST:event_jButtonTreatmentsActionPerformed

    private void jComboBoxTreatmentsSymptomsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTreatmentsSymptomsItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedOption = evt.getItem().toString();
            if (selectedOption.equals("Select ...")) {
                selectedOption = "";
            }
            
            query.setSymptoms(selectedOption);
        }
    }//GEN-LAST:event_jComboBoxTreatmentsSymptomsItemStateChanged

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        query.setSpeciality("");
        query.setLocation("");
        query.setLanguage("");
        query.setGender("");
        
        jComboBoxDoctorsSpeciality.getModel().setSelectedItem(jComboBoxDoctorsSpeciality.getModel().getElementAt(0));
        jComboBoxDoctorsLocation.getModel().setSelectedItem(jComboBoxDoctorsLocation.getModel().getElementAt(0));
        jComboBoxDoctorsLanguage.getModel().setSelectedItem(jComboBoxDoctorsLanguage.getModel().getElementAt(0));
        jRadioButtonAll.setSelected(true);
        
        // Get data from query
        String doctorQuery = query.buildDoctorsQuery();
        ArrayList data = sparql.listDoctors(doctorQuery);
        
        // Insert data in jList
        jListTextDoctors.setModel(html.createDoctorListItem(data));
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonResetHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetHospitalsActionPerformed
        query.setSpecialityHospitals("");
        query.setAddress("");
        query.setOpeningHours("00");
        query.setClosingHours("24");
        
        jComboBoxHospitalsSpeciality.getModel().setSelectedItem(jComboBoxHospitalsSpeciality.getModel().getElementAt(0));
        jComboBoxHospitalsLocation.getModel().setSelectedItem(jComboBoxHospitalsLocation.getModel().getElementAt(0));
        jComboBoxHospitalsOpening.getModel().setSelectedItem(jComboBoxHospitalsOpening.getModel().getElementAt(0));
        jComboBoxHospitalsClosing.getModel().setSelectedItem(jComboBoxHospitalsClosing.getModel().getElementAt(0));
        
        // Get data from query
        String hospitalQuery = query.buildHospitalsQuery();
        ArrayList data = sparql.listHospitals(hospitalQuery);

        // Insert data in jList
       jListTextHospitals.setModel(html.createHospitalListItem(data));
    }//GEN-LAST:event_jButtonResetHospitalsActionPerformed

    private void jComboBoxTreatmentsSymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTreatmentsSymptomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTreatmentsSymptomsActionPerformed

    private void jButtonResetTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetTreatmentsActionPerformed
        query.setSymptoms("");
        
        jComboBoxTreatmentsSymptoms.getModel().setSelectedItem(jComboBoxTreatmentsSymptoms.getModel().getElementAt(0));
        
        // Get data from query
        String treatmentQuery = query.buildTreatmentsQuery();
        ArrayList data = sparql.listTreatments(treatmentQuery);
        
        // Insert data in jList
        jListTextTreatments.setModel(html.createTreatmentListItem(data, false));
    }//GEN-LAST:event_jButtonResetTreatmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDoctors;
    private javax.swing.JButton jButtonDepartments;
    private javax.swing.JButton jButtonDoctors;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHospitals;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonResetHospitals;
    private javax.swing.JButton jButtonResetTreatments;
    private javax.swing.JButton jButtonSearchDoctors;
    private javax.swing.JButton jButtonSearchHospitals;
    private javax.swing.JButton jButtonSearchTreatments;
    private javax.swing.JButton jButtonTreatments;
    private javax.swing.JComboBox<String> jComboBoxDoctorsLanguage;
    private javax.swing.JComboBox<String> jComboBoxDoctorsLocation;
    private javax.swing.JComboBox<String> jComboBoxDoctorsSpeciality;
    private javax.swing.JComboBox<String> jComboBoxHospitalsClosing;
    private javax.swing.JComboBox<String> jComboBoxHospitalsLocation;
    private javax.swing.JComboBox<String> jComboBoxHospitalsOpening;
    private javax.swing.JComboBox<String> jComboBoxHospitalsSpeciality;
    private javax.swing.JComboBox<String> jComboBoxTreatmentsSymptoms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelLocation1;
    private javax.swing.JLabel jLabelSpeciality;
    private javax.swing.JLabel jLabelSpeciality1;
    private javax.swing.JLabel jLabelSymptoms;
    private javax.swing.JList<String> jListTextDepartments;
    private javax.swing.JList<String> jListTextDoctors;
    private javax.swing.JList<String> jListTextHospitals;
    private javax.swing.JList<String> jListTextTreatments;
    private javax.swing.JPanel jPanelCardLayout;
    private javax.swing.JPanel jPanelDepartments;
    private javax.swing.JPanel jPanelDoctors;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelHospitals;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelSearchDepartments;
    private javax.swing.JPanel jPanelSearchHospitals;
    private javax.swing.JPanel jPanelSearchTreatments;
    private javax.swing.JPanel jPanelTreatments;
    private javax.swing.JRadioButton jRadioButtonAll;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPaneListDoctors;
    private javax.swing.JScrollPane jScrollPaneListTextDepartments;
    private javax.swing.JScrollPane jScrollPaneListTextHospitals;
    private javax.swing.JScrollPane jScrollPaneListTextTreatments;
    // End of variables declaration//GEN-END:variables
}
